var Translator = function(){this.initialize.apply(this, arguments);}
Translator.prototype = {
    language    : 'Japanese' //English
,   dictionary  : {}
,   initialize: function() {
        this.dictionary = {
            '編集ビュー'                    : 'Edit View'
        ,   '俯瞰ビュー'                    : 'Bird View'
        ,   'Linkビュー'                    : 'Link View'
        ,   '編集\nビュー'                  : 'Edit\nView'
        ,   '俯瞰\nビュー'                  : 'Bird\nView'
        ,   'Link\nビュー'                  : 'Link\nView'
        ,   'ビュー設定'                    : 'View Setting'
        ,   '画像で保存'                    : 'Save As Image'
        ,   'ビューメニュー'                : 'View Menu'
        ,   '共通設定'                      : 'Common View Setting'
        ,   'ビュースタイル'                : 'View Style'
        ,   '独自スタイル'                  : 'Original Style'
        ,   'Bodyスタイル'                  : 'Body Style'
        ,   '背景画像'                      : 'BG Image'
        ,   '独自画像'                      : 'Original Image'
        ,   'Body画像'                      : 'Body Image'
        ,   '俯瞰ビュー設定'                : 'Bird View Setting'
        ,   '親階層数'                      : 'Parent Steps'
        ,   '１以上の数値を入力してください'   : 'Please input the number'
        ,   '子階層数'                      : 'Child Steps'
        ,   '表示方向'                      : 'Direction'
        ,   '水平方向間隔'                  : 'Horizontal Space'
        ,   '垂直方向間隔'                  : 'Vertical Space'
        ,   '上'                            : 'Up'
        ,   '下'                            : 'Down'
        ,   '左'                            : 'Left'
        ,   '右'                            : 'Right'
        ,   '俯瞰ビュー方向設定'            : 'Bird View Direction'
        ,   'ビューレベル'                  : 'View Level'
        ,   'シンプル'                      : 'Simple'
        ,   'ノーマル'                      : 'Normal'
        ,   'ブースト'                      : 'Boost'
        ,   'Linkビュー設定'                : 'Link View Setting'
        ,   'Link条件'                      : 'Link Filter'
        ,   '階層数'                        : 'Number Of Steps'
        ,   '最大'                          : 'Max'
        ,   '閉じる'                        : 'Close'
        ,   '戻る'                          : 'Back'
        ,   'OK'                            : 'OK'
        ,   '取消'                          : 'Cancel'
        ,   'ビュー'                        : 'View'
        ,   '切替'                          : 'Change'
        ,   'XML'                           : 'XML'
        ,   'JSONP'                         : 'JSONP'
        ,   '入力してF2で確定'              : 'Input and press F2'
        ,   'URLを入力してF2で確定'         : 'Input URL and press F2'
        ,   'Export / Import (F2でImport)'  : 'Export / Import (F2 to Import)'
        ,   'メニュー'                      : 'Menu'
        ,   '作成'                          : 'New\nBody'
        ,   '編集'                          : 'Edit'
        ,   '削除'                          : 'Delete'
        ,   '追加'                          : 'Add'
        ,   '検索'                          : 'Search'
        ,   '浮上'                          : 'Surface'
        ,   'ダイブ'                        : 'Dive'
        ,   '選択中メニュー'                : 'Select Menu'
        ,   'スタイル'                      : 'Style'
        ,   'コピー'                        : 'Copy'
        ,   '切り取り'                      : 'Cut'
        ,   '全て選択'                      : 'Select All'
        ,   '全て\n選択'                    : 'Select\nAll'
        ,   'そのBody自身あるいは親Bodyを貼り付けできません'  : 'Can not paste the body it self or parent body of current view'
        ,   '貼り付け'                      : 'Paste'
        ,   'Soul\n共有解除'                : 'Release\nSoul'
        ,   '色選択'                        : 'Select a color'
        ,   '対象'                          : 'Target'
        ,   '選択中のBody/Link'             : 'Selected Body/Link'
        ,   '標準のBodyスタイル'            : 'Default Body Style'
        ,   '標準のLinkスタイル'            : 'Default Link Style'
        ,   '選択中のビュー'                : 'Selected View'
        ,   '標準のビュースタイル'          : 'Default View Style'
        ,   '背景色'                        : 'BG Color'
        ,   '文字色'                        : 'Text Color'
        ,   'フォント'                      : 'Font'
        ,   '文字サイズ'                    : 'Font Size'
        ,   '文字サイズを入力してください'  : 'Please input the font size'
        ,   '文字左右位置'                  : 'Text Align'
        ,   'Link名称を入力してください'    : 'Please input the link name'
        ,   '該当するLinkが見つかりません'  : 'No such link found'
        ,   '(なし)'                        : '(None)'
        ,   '-'                             : '-'
        ,   '詳細'                          : 'Detail'
        ,   'Link絞り込み条件一覧'          : 'Link Filter Condition List'
        ,   '類似Soul一覧'                  : 'Similar Soul List'
        ,   'Body作成'                      : 'Create New Body'
        ,   '削除'                          : 'Delete'
        ,   'Soul共有解除'                  : 'Release Soul'
        ,   'ビュー内全体表示'              : 'Fit To View'
        ,   '全体\n表示'                    : 'See\nAll'
        ,   '新規ビューで開く'              : 'Open New View'
        ,   '選択Body間を結線'              : 'Connect Line Between Bodies'
        ,   'Body9個生成'                   : 'Create 9 Bodies'
        ,   'AI生成'                       : 'Generate by AI'
        ,   '長方形⇔角丸長方形'            : 'Change Shape Figure'
        ,   'ビュードッキング'              : 'Dock View'
        ,   'ビュードッキング解除'          : 'Undock View'
        ,   'ズーム\nイン'                  : 'Zoom\nIn'
        ,   'ズーム\nアウト'                : 'Zoom\nOut'
        ,   '保存\n読込'                    : 'Save &\nLoad'
        ,   '画像\n設定'                    : 'Image\nSetting'
        ,   '画像設定'                      : 'Image Setting'
        ,   'URL\n設定'                     : 'URL\nSetting'
        ,   'URL設定'                       : 'URL Setting'
        ,   '整形\n(連打)'                  : 'Format\n(Push!)'
        ,   '整形中...'                     : 'Formating...'
        ,   'Link\n条件'                    : 'Link\nCondi-\ntion'
        ,   'まとめて\n選択'                : 'Select\nLink\nGroup'
        ,   '選択\nSoul\nロック'            : 'Lock\nSelected\nSoul'
        ,   '画像\n出力'                    : 'Export\nImage'
        ,   '範囲\n選択'                    : 'Range\nSelect'
        ,   '範囲選択'                      : 'Range Select'
        ,   'ポインティングアニメーションON/OFF'    : 'Pointing Animation ON/OFF'
        ,   '新規\nビュー'                  : 'New\nView'
        ,   '休憩'                          : 'Break\nTime'
        ,   '休憩\n１'                      : 'Break\n1'
        ,   '休憩\n２'                      : 'Break\n2'
        ,   '新規\nビューで\n開く'          : 'Open\nNew View'
        ,   'ズームイン'                    : 'Zoom In'
        ,   'ズームアウト'                  : 'Zoom Out'
        ,   '前\nスライド'                  : 'Slide\nForward'
        ,   '後\nスライド'                  : 'Slide\nBackward'
        ,   '保存読込'                      : 'Save/Load'
        ,   '保存・読込メニュー'            : 'Save/Load Menu'
        ,   '範囲選択'                      : 'Range Select'
        ,   '新規ビュー'                    : 'New View'
        ,   '休憩１'                        : 'Break 1'
        ,   '休憩２'                        : 'Break 2'
        ,   '元に\n戻す'                    : 'Undo'
        ,   'やり\nなおす'                  : 'Redo'
        ,   '上方向'                        : 'Up'
        ,   '下方向'                        : 'Down'
        ,   '右方向'                        : 'Right'
        ,   '左方向'                        : 'Left'
        ,   '親階層\n＋'                    : 'Parent\nSteps\+'
        ,   '親階層\n－'                    : 'Parent\nSteps\-'
        ,   '子階層\n＋'                    : 'Child\nSteps\+'
        ,   '子階層\n－'                    : 'Child\nSteps\-'
        ,   'ビュー\nレベル\n＋'            : 'View\nLevel\+'
        ,   'ビュー\nレベル\n－'            : 'View\nLevel\-'
        ,   'ダイブ\n方向'                  : 'Direction\nDive'
        ,   '浮上\n方向'                    : 'Direction\nSurface'
        ,   '階層\n＋'                      : 'Steps\+'
        ,   '階層\n－'                      : 'Steps\-'
        ,   '間隔\n＋'                      : 'Space\+'
        ,   '間隔\n－'                      : 'Space\-'
        ,   'かつ'                          : 'And'
        ,   '又は'                          : 'Or'
        ,   'と同じ'                        : 'It is'
        ,   'と違う'                        : 'It is not'
        ,   '新しいMAP'                     : 'New Map'
        ,   'ヘルプ'                        : 'Help'
        ,   'MAPは保存しましたか？'         : 'Did you save your map?'
        ,   '名前をつけて保存'              : 'Save As'
        ,   'エラーが発生しました。保存できませんでした。'                  : 'An error occured. Failed to save Map.'
        ,   '\nはこのブラウザのストレージに既に存在します。上書きしますか？': '\nis already exists in this Browser\'s Storage. Do you want to overwrite?'
        ,   'このブラウザのストレージに保存しました。'  :   'Saved in this Browser\'s Storage.'
        ,   'MAPを削除しますか？'           : 'Are you sure you want to delete the MAP ?'
        ,   'ブラウザのストレージに保存されたMAP一覧'   : 'List Of The Maps Saved In This Browser\'s Storage'
        ,   '保存されたMAPがありません'     : 'Saved Map Not Exists'
        ,   '検索文字列を入力して下さい'    : 'Input the keyword to search'
        ,   '同一名称のSoulにジャンプ'      : 'Jump to the same text Soul'
        ,   'BodyとしてImport'              : 'Import as a Body'
        ,   'BodyとしてImportできるのはXML形式で保存されたMAPだけです'  : 'You can use [import as a Body] option only for a Map saved as XML'
        }
    }
,   t: function(_jptext) {
        if (this.language === 'Japanese') {
            return _jptext;
        }
        var ret = this.dictionary[_jptext];
        if (ret) {
            return ret;
        }
        else {
            return _jptext;
        }
    }
};
